//! Timezone definitions (port of the C `zones.h` / `zones.c`).
//!
//! The 46 timezones and their DST rules, packed using the `utz` format. The
//! abbreviations and names are provided as display strings.

use crate::watch::utz::{URulePacked, UZonePacked};

/// The packed DST rules.
pub const ZONE_RULES: [URulePacked; 20] = [
    URulePacked {
        from_year: 8,
        to_year: 255,
        on_dayofweek: 7,
        on_dayofmonth: 1,
        at_is_local_time: 1,
        at_hours: 2,
        at_inc_minutes: 0,
        letter: 1,
        in_month: 4,
        offset_hours: 0,
    },
    URulePacked {
        from_year: 8,
        to_year: 255,
        on_dayofweek: 7,
        on_dayofmonth: 1,
        at_is_local_time: 1,
        at_hours: 2,
        at_inc_minutes: 0,
        letter: 2,
        in_month: 10,
        offset_hours: 1,
    },
    URulePacked {
        from_year: 8,
        to_year: 255,
        on_dayofweek: 7,
        on_dayofmonth: 1,
        at_is_local_time: 1,
        at_hours: 2,
        at_inc_minutes: 0,
        letter: 1,
        in_month: 4,
        offset_hours: 0,
    },
    URulePacked {
        from_year: 8,
        to_year: 255,
        on_dayofweek: 7,
        on_dayofmonth: 1,
        at_is_local_time: 1,
        at_hours: 2,
        at_inc_minutes: 0,
        letter: 2,
        in_month: 10,
        offset_hours: 1,
    },
    URulePacked {
        from_year: 8,
        to_year: 255,
        on_dayofweek: 7,
        on_dayofmonth: 1,
        at_is_local_time: 1,
        at_hours: 2,
        at_inc_minutes: 0,
        letter: 1,
        in_month: 4,
        offset_hours: 0,
    },
    URulePacked {
        from_year: 1,
        to_year: 255,
        on_dayofweek: 7,
        on_dayofmonth: 1,
        at_is_local_time: 1,
        at_hours: 2,
        at_inc_minutes: 0,
        letter: 2,
        in_month: 10,
        offset_hours: 1,
    },
    URulePacked {
        from_year: 7,
        to_year: 255,
        on_dayofweek: 7,
        on_dayofmonth: 8,
        at_is_local_time: 1,
        at_hours: 2,
        at_inc_minutes: 0,
        letter: 2,
        in_month: 3,
        offset_hours: 1,
    },
    URulePacked {
        from_year: 7,
        to_year: 255,
        on_dayofweek: 7,
        on_dayofmonth: 1,
        at_is_local_time: 1,
        at_hours: 1,
        at_inc_minutes: 0,
        letter: 1,
        in_month: 11,
        offset_hours: 0,
    },
    URulePacked {
        from_year: 19,
        to_year: 255,
        on_dayofweek: 7,
        on_dayofmonth: 2,
        at_is_local_time: 0,
        at_hours: 3,
        at_inc_minutes: 0,
        letter: 0,
        in_month: 4,
        offset_hours: 0,
    },
    URulePacked {
        from_year: 23,
        to_year: 255,
        on_dayofweek: 7,
        on_dayofmonth: 2,
        at_is_local_time: 0,
        at_hours: 4,
        at_inc_minutes: 0,
        letter: 0,
        in_month: 9,
        offset_hours: 1,
    },
    URulePacked {
        from_year: 0,
        to_year: 255,
        on_dayofweek: 7,
        on_dayofmonth: 0,
        at_is_local_time: 0,
        at_hours: 1,
        at_inc_minutes: 0,
        letter: 1,
        in_month: 3,
        offset_hours: 1,
    },
    URulePacked {
        from_year: 0,
        to_year: 255,
        on_dayofweek: 7,
        on_dayofmonth: 0,
        at_is_local_time: 0,
        at_hours: 1,
        at_inc_minutes: 0,
        letter: 0,
        in_month: 10,
        offset_hours: 0,
    },
    URulePacked {
        from_year: 23,
        to_year: 255,
        on_dayofweek: 5,
        on_dayofmonth: 0,
        at_is_local_time: 1,
        at_hours: 0,
        at_inc_minutes: 0,
        letter: 1,
        in_month: 4,
        offset_hours: 1,
    },
    URulePacked {
        from_year: 23,
        to_year: 255,
        on_dayofweek: 4,
        on_dayofmonth: 0,
        at_is_local_time: 1,
        at_hours: 23,
        at_inc_minutes: 0,
        letter: 0,
        in_month: 10,
        offset_hours: 0,
    },
    URulePacked {
        from_year: 8,
        to_year: 255,
        on_dayofweek: 7,
        on_dayofmonth: 1,
        at_is_local_time: 1,
        at_hours: 2,
        at_inc_minutes: 0,
        letter: 1,
        in_month: 4,
        offset_hours: 0,
    },
    URulePacked {
        from_year: 7,
        to_year: 255,
        on_dayofweek: 7,
        on_dayofmonth: 0,
        at_is_local_time: 1,
        at_hours: 2,
        at_inc_minutes: 0,
        letter: 2,
        in_month: 9,
        offset_hours: 1,
    },
    URulePacked {
        from_year: 7,
        to_year: 255,
        on_dayofweek: 7,
        on_dayofmonth: 8,
        at_is_local_time: 1,
        at_hours: 2,
        at_inc_minutes: 0,
        letter: 2,
        in_month: 3,
        offset_hours: 1,
    },
    URulePacked {
        from_year: 7,
        to_year: 255,
        on_dayofweek: 7,
        on_dayofmonth: 1,
        at_is_local_time: 1,
        at_hours: 1,
        at_inc_minutes: 0,
        letter: 1,
        in_month: 11,
        offset_hours: 0,
    },
    URulePacked {
        from_year: 13,
        to_year: 255,
        on_dayofweek: 5,
        on_dayofmonth: 23,
        at_is_local_time: 1,
        at_hours: 2,
        at_inc_minutes: 0,
        letter: 2,
        in_month: 3,
        offset_hours: 1,
    },
    URulePacked {
        from_year: 13,
        to_year: 255,
        on_dayofweek: 7,
        on_dayofmonth: 0,
        at_is_local_time: 1,
        at_hours: 1,
        at_inc_minutes: 0,
        letter: 1,
        in_month: 10,
        offset_hours: 0,
    },
];

/// The packed zone definitions (46 zones).
pub const ZONE_DEFNS: [UZonePacked; 46] = [
    UZonePacked {
        offset_inc_minutes: -44,
        rules_idx: 0,
        rules_len: 0,
        abrev_formatter: 0,
    },
    UZonePacked {
        offset_inc_minutes: -40,
        rules_idx: 0,
        rules_len: 0,
        abrev_formatter: 4,
    },
    UZonePacked {
        offset_inc_minutes: -36,
        rules_idx: 16,
        rules_len: 2,
        abrev_formatter: 8,
    },
    UZonePacked {
        offset_inc_minutes: -32,
        rules_idx: 16,
        rules_len: 2,
        abrev_formatter: 14,
    },
    UZonePacked {
        offset_inc_minutes: -28,
        rules_idx: 16,
        rules_len: 2,
        abrev_formatter: 19,
    },
    UZonePacked {
        offset_inc_minutes: -28,
        rules_idx: 0,
        rules_len: 0,
        abrev_formatter: 24,
    },
    UZonePacked {
        offset_inc_minutes: -24,
        rules_idx: 16,
        rules_len: 2,
        abrev_formatter: 28,
    },
    UZonePacked {
        offset_inc_minutes: -24,
        rules_idx: 0,
        rules_len: 0,
        abrev_formatter: 33,
    },
    UZonePacked {
        offset_inc_minutes: -20,
        rules_idx: 16,
        rules_len: 2,
        abrev_formatter: 37,
    },
    UZonePacked {
        offset_inc_minutes: -16,
        rules_idx: 6,
        rules_len: 2,
        abrev_formatter: 42,
    },
    UZonePacked {
        offset_inc_minutes: -16,
        rules_idx: 0,
        rules_len: 0,
        abrev_formatter: 47,
    },
    UZonePacked {
        offset_inc_minutes: -16,
        rules_idx: 8,
        rules_len: 2,
        abrev_formatter: 51,
    },
    UZonePacked {
        offset_inc_minutes: -12,
        rules_idx: 0,
        rules_len: 0,
        abrev_formatter: 59,
    },
    UZonePacked {
        offset_inc_minutes: -10,
        rules_idx: 6,
        rules_len: 2,
        abrev_formatter: 67,
    },
    UZonePacked {
        offset_inc_minutes: -8,
        rules_idx: 10,
        rules_len: 2,
        abrev_formatter: 72,
    },
    UZonePacked {
        offset_inc_minutes: 0,
        rules_idx: 0,
        rules_len: 0,
        abrev_formatter: 80,
    },
    UZonePacked {
        offset_inc_minutes: 0,
        rules_idx: 10,
        rules_len: 2,
        abrev_formatter: 84,
    },
    UZonePacked {
        offset_inc_minutes: 4,
        rules_idx: 0,
        rules_len: 0,
        abrev_formatter: 92,
    },
    UZonePacked {
        offset_inc_minutes: 4,
        rules_idx: 10,
        rules_len: 2,
        abrev_formatter: 96,
    },
    UZonePacked {
        offset_inc_minutes: 8,
        rules_idx: 12,
        rules_len: 2,
        abrev_formatter: 102,
    },
    UZonePacked {
        offset_inc_minutes: 8,
        rules_idx: 0,
        rules_len: 0,
        abrev_formatter: 108,
    },
    UZonePacked {
        offset_inc_minutes: 8,
        rules_idx: 18,
        rules_len: 2,
        abrev_formatter: 112,
    },
    UZonePacked {
        offset_inc_minutes: 8,
        rules_idx: 10,
        rules_len: 2,
        abrev_formatter: 102,
    },
    UZonePacked {
        offset_inc_minutes: 12,
        rules_idx: 0,
        rules_len: 0,
        abrev_formatter: 117,
    },
    UZonePacked {
        offset_inc_minutes: 12,
        rules_idx: 0,
        rules_len: 0,
        abrev_formatter: 121,
    },
    UZonePacked {
        offset_inc_minutes: 12,
        rules_idx: 0,
        rules_len: 0,
        abrev_formatter: 125,
    },
    UZonePacked {
        offset_inc_minutes: 14,
        rules_idx: 0,
        rules_len: 0,
        abrev_formatter: 129,
    },
    UZonePacked {
        offset_inc_minutes: 16,
        rules_idx: 0,
        rules_len: 0,
        abrev_formatter: 141,
    },
    UZonePacked {
        offset_inc_minutes: 22,
        rules_idx: 0,
        rules_len: 0,
        abrev_formatter: 145,
    },
    UZonePacked {
        offset_inc_minutes: 23,
        rules_idx: 0,
        rules_len: 0,
        abrev_formatter: 149,
    },
    UZonePacked {
        offset_inc_minutes: 26,
        rules_idx: 0,
        rules_len: 0,
        abrev_formatter: 155,
    },
    UZonePacked {
        offset_inc_minutes: 28,
        rules_idx: 0,
        rules_len: 0,
        abrev_formatter: 161,
    },
    UZonePacked {
        offset_inc_minutes: 32,
        rules_idx: 0,
        rules_len: 0,
        abrev_formatter: 33,
    },
    UZonePacked {
        offset_inc_minutes: 32,
        rules_idx: 0,
        rules_len: 0,
        abrev_formatter: 165,
    },
    UZonePacked {
        offset_inc_minutes: 32,
        rules_idx: 0,
        rules_len: 0,
        abrev_formatter: 170,
    },
    UZonePacked {
        offset_inc_minutes: 32,
        rules_idx: 0,
        rules_len: 0,
        abrev_formatter: 174,
    },
    UZonePacked {
        offset_inc_minutes: 36,
        rules_idx: 0,
        rules_len: 0,
        abrev_formatter: 179,
    },
    UZonePacked {
        offset_inc_minutes: 36,
        rules_idx: 0,
        rules_len: 0,
        abrev_formatter: 183,
    },
    UZonePacked {
        offset_inc_minutes: 38,
        rules_idx: 0,
        rules_len: 0,
        abrev_formatter: 187,
    },
    UZonePacked {
        offset_inc_minutes: 38,
        rules_idx: 2,
        rules_len: 2,
        abrev_formatter: 192,
    },
    UZonePacked {
        offset_inc_minutes: 40,
        rules_idx: 0,
        rules_len: 0,
        abrev_formatter: 198,
    },
    UZonePacked {
        offset_inc_minutes: 40,
        rules_idx: 4,
        rules_len: 2,
        abrev_formatter: 203,
    },
    UZonePacked {
        offset_inc_minutes: 40,
        rules_idx: 0,
        rules_len: 2,
        abrev_formatter: 203,
    },
    UZonePacked {
        offset_inc_minutes: 40,
        rules_idx: 0,
        rules_len: 0,
        abrev_formatter: 209,
    },
    UZonePacked {
        offset_inc_minutes: 48,
        rules_idx: 0,
        rules_len: 0,
        abrev_formatter: 214,
    },
    UZonePacked {
        offset_inc_minutes: 48,
        rules_idx: 14,
        rules_len: 2,
        abrev_formatter: 218,
    },
];

/// The display names for each zone (7 chars each, matching the C `zone_names`).
pub const ZONE_NAMES: [&str; 46] = [
    "Sanoa", "HNLULU", "Anchrg", "SeattL", "Denver", "Arizona", "Chcago", "Regina", "NYork ",
    "haLifa", "n&naUs", "Stiago", "SaoPLo", "St Jns", "  Nuuk", "   UtC", " Londn", " Lagos",
    "BerLIN", "Cairo ", "n&apto", "1sraeL", "hLs nki", "Nairob", "Ryadh ", "n&scou", "+ehran",
    " dubai", " 1ndIa", " Nepal", "8urn&a", "BngkOk", "Shnghi", "honKon", "Sngpor", " Perth",
    " Tokyo", "SeouL ", "Daruin", "AdLaid", "BrsbNe", " hobrt", "Sy0ney", " GuaN7", "+arawa",
    "AuckLd",
];

/// The number of zones.
pub const NUM_ZONE_NAMES: usize = 46;
